// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCa-p2s0OGtdrmXl4gqGMYhQmvon0L-XVg',
    appId: '1:142063010866:web:1b0214e257ff86bdf4e82b',
    messagingSenderId: '142063010866',
    projectId: 'whatsapp-messenger-69425',
    authDomain: 'whatsapp-messenger-69425.firebaseapp.com',
    storageBucket: 'whatsapp-messenger-69425.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHnxC1ky-WXtfoH896D-rMvgCsTMRWW-s',
    appId: '1:142063010866:android:6a67ab03d5b100bef4e82b',
    messagingSenderId: '142063010866',
    projectId: 'whatsapp-messenger-69425',
    storageBucket: 'whatsapp-messenger-69425.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5ThTxM7Fkphy-m8eBOfFE2JpzYLnIGEM',
    appId: '1:142063010866:ios:7800f723937967d3f4e82b',
    messagingSenderId: '142063010866',
    projectId: 'whatsapp-messenger-69425',
    storageBucket: 'whatsapp-messenger-69425.appspot.com',
    iosClientId: '142063010866-n6qe3p3jt2hn4jijdh3i7iik81n583b7.apps.googleusercontent.com',
    iosBundleId: 'com.example.whatsappMessenger',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5ThTxM7Fkphy-m8eBOfFE2JpzYLnIGEM',
    appId: '1:142063010866:ios:41690579babd4629f4e82b',
    messagingSenderId: '142063010866',
    projectId: 'whatsapp-messenger-69425',
    storageBucket: 'whatsapp-messenger-69425.appspot.com',
    iosClientId: '142063010866-p9f6h5uvcf5h02s3mv4o2bccsgmf0pdm.apps.googleusercontent.com',
    iosBundleId: 'com.example.whatsappMessenger.RunnerTests',
  );
}
